api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

#    swagger:
#         api_keys:
#             apiKey:
#                name: Authorization
#                type: header

    collection:
        pagination:
            page_parameter_name: _page
            items_per_page: 10
            client_items_per_page: true #Disabled by default
            items_per_page_parameter_name: itemsPerPage
            maximum_items_per_page: 7
            #client_enabled: true
            #enabled_parameter_name: pagination

    exception_to_status:
        App\Exception\EmptyBodyException: 400
