vich_uploader:
  db_driver: orm

  mappings:
    courses:
      uri_prefix: /images/courses
      #upload_destination: "%kernel.project_dir%/public/images/courses"
      upload_destination: images/courses
      #Decide how uploaded files would be renamed
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      #directory_namer:
        #service: vich_uploader.namer_directory_current_date_time
        #options: {date_time_format: 'Y/m/d/h'} # will create directory "2018/12/27" for current date "2018-12-27"
      delete_on_remove: true # whether to delete file upon removal of entity
      inject_on_load: true # whether to inject a File upon load
